parameters:
#    mg_mensajeria.example.class: MG\MensajeriaBundle\Example

services:
#    mg_mensajeria.example:
#        class: %mg_mensajeria.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
